
UP = (0, -1)
DOWN = (0, 1)
LEFT = (-1, 0)
RIGHT = (1, 0)

NUM_ACTIONS = 4
ACTIONS = [UP, DOWN, LEFT, RIGHT]

NUM_FEATURES=24

#--------------------------------------

GRID_W = 10
GRID_H = 10

INITIAL_SNAKE_POS = [(0, 2), (0, 1), (0, 0)]

NUM_FOOD = 9

NUM_EPISODES = 5
MAX_STEPS = 1500

NUM_GENERATIONS=300
NUM_PARENTS_MATING=8
SOL_PER_POP=50
MUTATION_PERCENT_GENES=10
GENE_SPACE_LOW=-2.0
GENE_SPACE_HIGH=2.0
NUM_TESTING_STEPS = 1000